---
title: "Data Wrangling"
author: "Austin Hsin"
date: "2023-09-19"
output: html_document
---

```{r setup, echo = FALSE, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Code litters_data import

```{r litters_data import}
litters_data = read_csv(file = "./data_import_examples/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)
names(litters_data)
skimr::skim(litters_data)
```

## Code litters_data wrangling

```{r litters_data clean}
litters_data = read_csv(file = "./data_import_examples/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)

```

## Code pups_data

```{r pups}
pups_data = read_csv(file = "./data_import_examples/FAS_pups.csv")
skimr::skim(pups_data)
names(pups_data)
pups_data = read_csv(file = "./data_import_examples/FAS_pups.csv",
  col_types = cols(
    `Litter Number` = col_character(),
    `Sex` = col_integer(),
    `PD ears` = col_integer(),
    `PD eyes` = col_double(),
    `PD pivot` = col_integer(),
    `PD walk` = col_double(),
  )
)
```

## Code Reading Non CSV Files

```{r Non CSV - xlsx + sas}
library(readxl)
mlb11_data = read_excel("./data_import_examples/mlb11.xlsx", n_max = 20)
head(mlb11_data, 5)

library(haven)
pulse_data = read_sas("./data_import_examples/public_pulse_data.sas7bdat")
head(pulse_data, 5)
```